name: RareItemHunter2
main: com.ne0nx3r0.rih.RareItemHunterPlugin
version: '2.4.15a'
load: STARTUP
database: false
description: Rare Item Hunter
commands:
    ri2:
      description: RareItems commands
permissions: 
# All
  rih.tester:
    description: Permission to test ALL the things
    default: false